---
language: python
python: ["2.7", "3.5"]
dist: trusty
sudo: True
group: beta
env:
    - platform: openbsd60
    - &openbsd59 platform=openbsd59
    - &openbsd56 platform=openbsd56
    - platform: xenial
    - platform: trusty
    - &jessie platform=jessie
    - &wheezy platform=wheezy
    - platform: precise
    - &stretch platform=stretch
matrix:
    fast_finish: True
    allow_failures:
        - python: "3.5"
        - env: *openbsd59
        - env: *openbsd56
        - env: *jessie
        - env: *wheezy
        - env: *stretch
cache:
  - pip
  - directories:
      - $HOME/.pre-commit

install:
  - sudo apt-get update
  - sudo apt-get install -y linux-headers-$(uname -r) virtualbox
  - wget https://releases.hashicorp.com/vagrant/1.9.1/vagrant_1.9.1_x86_64.deb
  - sudo dpkg -i vagrant_1.9.1_x86_64.deb
  - pip install -r tests/requirements.txt | cat
  - ansible-galaxy install git+file://$(pwd),$(git rev-parse --abbrev-ref HEAD) -p .molecule/roles
  - molecule dependency

script:
  - pre-commit run --all-files
  - molecule test --platform $platform

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  email: false
  on_failure: never
